### ISSUE TITLE
Context propagation issue across threads in Lambda

### ISSUE THREAD

**Issue by awssandra** [aws/aws-xray-java-agent#16] opened 2019-12-01 22:45 UTC
This might be an X-Ray issue as DiSCo does this all in a very low level. It may be our transaction context resolver isn't properly detecting the facade segment in new threads. More investigation needed.

**Reproduction**
```
Subsegment subsegment = AWSXRay.beginSubsegment("handleRequest");
Future<Void> eventFuture = sendEvent(locationId);
...
eventFuture.get();
...
AWSXRay.endSubsegment();
```
```
private Future<Void> sendEvent(String message) {
    return executor.submit(() -> {
        Subsegment subsegment = AWSXRay.beginSubsegment("sendEvent");
        try {
            sns.publish(System.getenv("MAINTENANCE_TOPIC_ARN"), message);
            return null;
        }
        finally {
            AWSXRay.endSubsegment();
        }
    });
}
```

**Comment by willarmiros** [comment] 2020-04-29 14:56
Closing since the issue is resolved.

**Closed by willarmiros** 2020-04-29 14:56 UTC
